### ISSUE TITLE
Feedback Project management. 

### ISSUE THREAD

**Issue by ivanmilara** [palosaari/fablab#3]
Very good job. Still some additional information required, especially to explain how did you generate the website content. 

# Principles and Practice Feedback #

## From Assessment guide ##

* [x] Sketched your final project idea/s
* [x] Described what it will do and who will use it

## Comments ##

The website and project description are ok. Any of the three projects are doable in Fab Lab. 

# Project Management #
## From Assessment guide ##

* [x] Made a website and described how you did it
* [x] Created a section about yourself on that website
* [x] Added a page with a sketch and description of your final project idea(s)
* [x] Documented steps for creating your Git repository and adding files to it
* [x] Pushed to the class GitLab

### About me website ###

OK

### Description of the GIT process ###
* Explain what is GIT and what is github.
* You are missing pull / fetch from the basics commands.
* Include the command you used to generate your public/private key pair. 
* You should also explain how did you create the local repo
* Explain better how do you upload your source files to your repo (git commands you used)

### Description of the website ###

* Explain a little bit what is a website static generator, what is mkdocs and how is a template. Present briefly the structure of your site
* Explain what is markdown and how you used markdown to  generate the different sites.
* Explain what is mkdocs.yml and how you have modified it.

**Comment by palosaari** [comment]
It is now updated.

**Comment by ivanmilara** [comment]
Hi, 

It is almost done. I will inform Jani that this work is ready. But, in the meanwhile you should do these small additions. When they are ready I can close this issue. 

* Please, explain what is the command you need to use to generate the ssh key if you do not have it
*  Explain in one sentence what is gh command line. 

Some typos: 
* on my chase -> on my case

**Comment by palosaari** [comment]
Hi,
It is mentioned already:
"I already had ssh keys because I usually use them in many places. ssh keys can be generated with the ssh-keygen command, for example."

There is likely other possibilities too , but this command is on my linux desktop

[crope@localhost ~]$ ssh-keygen 
Generating public/private rsa key pair.
Enter file in which to save the key (/home/crope/.ssh/id_rsa): test_ssh_key 
Enter passphrase (empty for no passphrase): 
Enter same passphrase again: 
Your identification has been saved in test_ssh_key
Your public key has been saved in test_ssh_key.pub
The key fingerprint is:
SHA256:ig5wtVkI9wHLx+gdd3bl0jWf81Hne71ZR4PAvxGXqjw crope@localhost.localdomain
The key's randomart image is:
+---[RSA 3072]----+
|  . o..   ..  ..=|
|   + * .   ..=.=*|
|    * * . o +.*=+|
|   o * o o . = .B|
|. . + . S . . o.*|
| o   . .   E .  *|
|  . . .     .  o |
|   o             |
|    .            |
+----[SHA256]-----+
[crope@localhost ~]$ file test_ssh_key
test_ssh_key: OpenSSH private key
[crope@localhost ~]$ file test_ssh_key.pub 
test_ssh_key.pub: OpenSSH RSA public key
[crope@localhost ~]$

**Comment by ivanmilara** [comment]
Yep, that is correct I missed that. Just mention what is gh, and that would do it. I will close the issue.
